# Generated by Django 2.0.7 on 2018-08-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almoxarifado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almoxarifado_central', models.BooleanField(default=True)),
                ('descricao_almoxarifado', models.CharField(max_length=255, verbose_name='Descrição do Almoxarifado')),
            ],
            options={
                'verbose_name': 'Almoxarifado',
                'verbose_name_plural': 'Almoxarifados',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(max_length=255, verbose_name='Nome do Departamento')),
                ('centro_custo', models.FloatField(verbose_name='Centro de Custo')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secretaria', models.CharField(max_length=255, verbose_name='Nome da Secretaria')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='secretaria_relacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.Secretaria'),
        ),
    ]
