# Generated by Django 2.0.7 on 2018-08-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secretaria_user',
            field=models.CharField(blank=True, choices=[('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação'), ('FINANCA_ADMINISTRCAO', 'Finanças e Administração'), ('ESPORT_CULT_TURI', 'Esporte Cultura e Turismo'), ('ASSISTENCIA_SOCIAL', 'Assitência Social'), ('INFRA', 'Infra Estrutura')], max_length=255, null=True, verbose_name='Secretaria do Usuário'),
        ),
    ]
