# Generated by Django 2.0.7 on 2018-08-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_secretaria_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_user',
            field=models.CharField(blank=True, choices=[('USUARIO_COMUM', 'Usuário Comum'), ('USUARIO_ADMINISTRATIVO', 'Usuário Administrativo'), ('USUARIO_SECRETARIO', 'Usuário Secretario')], max_length=255, null=True, verbose_name='Profile de Usuário'),
        ),
    ]
