# Generated by Django 2.0.7 on 2018-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secretaria_user',
            field=models.CharField(blank=True, choices=[('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação'), ('FINANCA_ADMINISTRCAO', 'Finanças e Administração'), ('ESPORT_CULT_TURI', 'Esporte Cultura e Turismo'), ('ASSISTENCIA_SOCIAL', 'Assitência Social'), ('INFRA', 'Infra Estrutura'), ('GABINETE', 'Gabinete')], max_length=255, null=True, verbose_name='Secretaria do Usuário'),
        ),
    ]
