# Generated by Django 2.1.2 on 2018-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180926_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='almoxarifado_user',
            field=models.ForeignKey(on_delete=False, to='secretaria.Almoxarifado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departamento_user',
            field=models.ForeignKey(on_delete=False, to='secretaria.Departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secretaria_user',
            field=models.ForeignKey(on_delete=False, related_name='Secretaria', to='secretaria.Secretaria'),
        ),
    ]
