# Generated by Django 2.1.2 on 2018-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181001_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usuario_permissao',
            field=models.CharField(choices=[('Padrão', 'Padrão'), ('Secretario', 'Secretario'), ('Administrativo', 'Administrativo'), ('Entrega', 'Entrega')], default='Padrão', max_length=20),
        ),
    ]
