# Generated by Django 2.1.2 on 2018-10-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181004_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='almoxarifado_user',
            field=models.ForeignKey(null=True, on_delete=False, to='secretaria.Almoxarifado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departamento_user',
            field=models.ForeignKey(null=True, on_delete=False, to='secretaria.Departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secretaria_user',
            field=models.ForeignKey(null=True, on_delete=False, related_name='Secretaria', to='secretaria.Secretaria'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario_administrativo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario_entrega',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario_padrao',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario_secretario',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
