# Generated by Django 2.0.7 on 2018-09-26 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_material', models.CharField(max_length=100, verbose_name='Descrição do Material')),
                ('codigo_material', models.IntegerField()),
                ('almoxarifado_relacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.Almoxarifado')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Materiais_Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_material', models.FloatField(verbose_name='Quantidade de Material')),
                ('quantidade_aprovada', models.FloatField(blank=True, null=True, verbose_name='Quantidade Aprovada')),
                ('relacionamento_materiais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Materiais')),
            ],
            options={
                'verbose_name': 'Material da Solicitação',
                'verbose_name_plural': 'Material das Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.PositiveSmallIntegerField(choices=[(1, 'Requisição'), (2, 'Devolução')], verbose_name='Tipo de Movimentação')),
                ('movimentacao_descricao', models.CharField(max_length=255, verbose_name='Descrição de Movimentação')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Aberta'), (False, 'fechada')], default=True, verbose_name='Status da Solicitação')),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('numero_descricao', models.CharField(max_length=32, unique=True)),
                ('requisicao_enviado', models.BooleanField(default=False)),
                ('requisicao_secretario', models.BooleanField(default=False)),
                ('requisicao_processamento', models.BooleanField(default=False)),
                ('requisicao_transito', models.BooleanField(default=False)),
                ('requisicao_recebido', models.BooleanField(default=False)),
                ('almoxarifado_relacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.Almoxarifado')),
                ('departamento_relacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.Departamento')),
                ('movimentacao_relacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Movimentacao')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'permissions': (('administrativo_permissao', 'administrativo permissao'), ('entrega_permissao', 'entrega permissao'), ('secretario_permissao', 'secretario permissao')),
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_unidade', models.CharField(blank=True, choices=[('M²', 'm²'), ('KG', 'kg'), ('UN', 'un'), ('M', 'm'), ('CM', 'cm'), ('MM', 'mm')], max_length=255, null=True, verbose_name='Tipo de Unidade')),
                ('unidade_descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Unidade')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AddField(
            model_name='materiais_solicitacao',
            name='relacionamento_solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Solicitacao'),
        ),
        migrations.AddField(
            model_name='materiais_solicitacao',
            name='unidade_relacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Unidade'),
        ),
    ]
