# Generated by Django 2.0.7 on 2018-07-31 16:22

from django.db import migrations, models
import django.db.models.deletion
import solicitacao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_material', models.CharField(max_length=255, verbose_name='Descrição do Material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Materiais_Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Material')),
                ('quantidade_material', models.FloatField(verbose_name='Quantidade de Material')),
                ('relacionamento_materiais', models.ForeignKey(on_delete='Relacionamento com Materiais', to='solicitacao.Materiais')),
            ],
            options={
                'verbose_name': 'Material da Solicitação',
                'verbose_name_plural': 'Material das Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.PositiveSmallIntegerField(choices=[(1, 'Requisição'), (2, 'Devolução')], verbose_name='Tipo de Movimentação')),
                ('movimentacao_descricao', models.CharField(max_length=255, verbose_name='Descrição de Movimentação')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('descricao_solicitacao', models.CharField(max_length=255, verbose_name='Descrição da Solicitacao')),
                ('numero_descricao', models.CharField(default=solicitacao.models.numero_solicitacao, max_length=255)),
                ('data_status', models.DateField(verbose_name='Data de Modificação do Status da Solicitação')),
                ('departamento_relacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.Departamento')),
                ('movimentacao_relacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Movimentacao')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_solicitacao', models.CharField(choices=[('ENVIADO', 'Enviado'), ('PROCESSAMENTO', 'Processamento'), ('EM TRANSITO', 'Em Trânsito'), ('RECEBIDO', 'Recebido')], max_length=255, verbose_name='Status Atual da Solicitação')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_unidade', models.CharField(blank=True, choices=[('M²', 'm²'), ('KG', 'kg'), ('UN', 'un'), ('M', 'm'), ('CM', 'cm'), ('MM', 'mm')], max_length=255, null=True, verbose_name='Tipo de Unidade')),
                ('unidade_descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Unidade')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status_relacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Status'),
        ),
        migrations.AddField(
            model_name='materiais_solicitacao',
            name='relacionamento_solicitacao',
            field=models.ForeignKey(on_delete='Relacionamento com Solicitacao', to='solicitacao.Solicitacao'),
        ),
        migrations.AddField(
            model_name='materiais_solicitacao',
            name='unidade_relacionamento',
            field=models.ForeignKey(on_delete='Relacionamento com a unidade', to='solicitacao.Unidade'),
        ),
    ]
