# Generated by Django 2.0.7 on 2018-07-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_solicitacao',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('PROCESSAMENTO', 'Processamento'), ('EM TRANSITO', 'Em Trânsito'), ('RECEBIDO', 'Recebido')], default='ENVIADO', max_length=255, verbose_name='Status Atual da Solicitação'),
        ),
    ]
