# Generated by Django 2.1.2 on 2018-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='requisicao_enviado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='requisicao_processamento',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='requisicao_recebido',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='requisicao_secretario',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='requisicao_transito',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
