# Generated by Django 2.0.7 on 2018-08-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiais_solicitacao',
            name='descricao_material',
        ),
    ]
