# Generated by Django 2.0.7 on 2018-08-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20180731_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='departamento_relacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.Departamento'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='movimentacao_relacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicitacao.Movimentacao'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status_relacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicitacao.Status'),
        ),
    ]
