# Generated by Django 2.0.7 on 2018-08-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_remove_materiais_solicitacao_descricao_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiais',
            name='unidade_relacionamento',
        ),
    ]
