# Generated by Django 2.0.7 on 2018-09-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_remove_materiais_unidade_relacionamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'permissions': (('permission_code', 'Acesso negado'),), 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
