# Generated by Django 2.0.7 on 2018-09-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_auto_20180910_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'permissions': (('administrativo_permissao', 'pode acessar'), ('entrega_permissao', 'pode acessar')), 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
