# Generated by Django 2.0.7 on 2018-09-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_auto_20180910_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'permissions': (('administrativo_permissao', 'administrativo'), ('entrega_permissao', 'entrega')), 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
