# Generated by Django 2.0.7 on 2018-08-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_auto_20180801_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data_status',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Modificação do Status da Solicitação'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status_relacionamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Status'),
        ),
    ]
