# Generated by Django 2.0.7 on 2018-08-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0007_auto_20180801_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='status_relacionamento',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='requisicao_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='requisicao_processamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='requisicao_recebido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='requisicao_transito',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
