# Generated by Django 2.0.7 on 2018-09-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0007_auto_20180910_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'permissions': (('administrativo_permissao', 'administrativo'),), 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
