# Generated by Django 2.0.7 on 2018-09-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0008_auto_20180910_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
