# Generated by Django 2.0.7 on 2018-08-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0008_auto_20180802_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_status',
        ),
    ]
