# Generated by Django 2.0.7 on 2018-08-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0009_remove_solicitacao_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiais_solicitacao',
            name='quantidade_aprovada',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantidade Aprovada'),
        ),
    ]
