# Generated by Django 2.0.7 on 2018-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0010_materiais_solicitacao_quantidade_aprovada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='teste',
            field=models.CharField(default='teste', max_length=50, verbose_name='teste'),
        ),
    ]
