# Generated by Django 2.0.7 on 2018-09-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0010_auto_20180910_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'permissions': (('entrega_permissao', 'entrega permissao'),), 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
