# Generated by Django 2.0.7 on 2018-09-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0011_auto_20180911_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'permissions': (('administrativo_permissao', 'administrativo permissao'),), 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
