# Generated by Django 2.0.7 on 2018-09-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0012_auto_20180911_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
