# Generated by Django 2.0.7 on 2018-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0012_remove_solicitacao_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.BooleanField(choices=[(True, 'Aberta'), (False, 'fechada')], default=True, verbose_name='Status da Solicitação'),
        ),
    ]
