# Generated by Django 2.0.7 on 2018-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0013_auto_20180911_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'permissions': (('administrativo_permissao', 'administrativo permissao'), ('entrega_permissao', 'entrega permissao')), 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
