# Generated by Django 2.0.7 on 2018-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0014_auto_20180911_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='requisicao_secretario',
            field=models.BooleanField(default=False),
        ),
    ]
