# Generated by Django 2.0.7 on 2018-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0015_auto_20180807_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiais',
            name='descricao_material',
            field=models.CharField(max_length=100, verbose_name='Descrição do Material'),
        ),
    ]
